### ISSUE TITLE
Problem with predicting sign language from cropped images

### ISSUE THREAD

**Issue by professional-procrastinator** [Endless-Debugger/react-frontend-asl-sign#1]
![image](https://user-images.githubusercontent.com/69335199/145969571-8e36a106-b20b-4619-af30-05cefcd0b400.png)
This error pops up when you crop an image, and then click on the predict button.

I opened the network tab to see details about the request, and, yes, as you can see, the server must be working very hard to predict nothing.
![image](https://user-images.githubusercontent.com/69335199/145969785-8f880e08-3e10-447f-b763-ad4b21cdf391.png)

Nothing is even being sent to the server, and therefore, it cannot do anything but return an internal server error.

Browser - MS Edge - Version 97.0.1072.28 (Official build) beta (64-bit) 
OS - Windows 10

**Comment by Endless-Debugger** [comment]
duck you 👆

**Comment by Endless-Debugger** [comment]
sahi kar diya bhai

**Comment by Endless-Debugger** [comment]
check kar

**Comment by professional-procrastinator** [comment]
![image](https://user-images.githubusercontent.com/69335199/145970767-9ea8ff9b-9459-4ec1-8ff1-61bedebad7df.png)
works 😃

**Comment by Endless-Debugger** [comment]
:chappal:

**Comment by Endless-Debugger** [comment]
close kardiya

**Comment by Endless-Debugger** [comment]
nooob
